#version: '1'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=linkconverter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

